# Font Configuration
font_family      Hack Nerd Font Regular
bold_font        Hack Nerd Font Bold
italic_font      Hack Nerd Font Italic
bold_italic_font Hack Nerd Font Bold Italic

font_size 12.0

modify_font baseline 0

# Cursor Configuration
cursor                none
cursor_shape          block
cursor_blink_interval 0

# Mouse Configuration
mouse_hide_wait -1
focus_follows_mouse no

# Tab Bar
tab_bar_style powerline
tab_powerline_style angled
tab_bar_align left
tab_bar_background #282828

active_tab_foreground #282828
active_tab_background #fabd2f
inactive_tab_foreground #fabd2f
inactive_tab_background #282828

# Underlines
scrollback_lines 200000


# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME

background #282828

map cmd+plus change_font_size all +1.0
map cmd+equal change_font_size all +1.0
map shift+cmd+equal change_font_size all +1.0
map cmd+minus change_font_size all -1.0
map shift+cmd+minus change_font_size all -1.0
